### ISSUE TITLE
Assets paths added to pubscpec.yaml have wrong backslash '\' character on Windows

### ISSUE THREAD

**Issue by Ricardo-MT** [rutvik110/asset_manager_cli#22]
Description:
After running the command "asset_manager add" in cmd on a Windows machine the resulting paths added to my pubscpec.yaml file have an incorrect basckslash '\' character instead of the correct '/', resulting in flutter not being able to successfully run the project. Also, the paths don´t have the ending '/' character.

Issues:
1. Incorrect backslash '\' character instead of correct '/'.
2. Paths don´t have the ending '/' character.

Content in pubspec.yaml after running the package:
```yaml
flutter:

  assets:
    - assets\audio
    - assets\images
    - assets\images\1_Interiors
    - assets\images\1_Interiors\32x32
    - assets\images\1_Interiors\32x32\Old_Stuff
    - assets\images\1_Interiors\32x32\Room_Bulder_subfiles_32x32
    - assets\images\1_Interiors\32x32\Theme_Sorter_32x32
    - assets\images\1_Interiors\32x32\Theme_Sorter_Black_Shadow_32x32
```

Resulting error when running the project:
```bash
Launching lib/main_development.dart on Windows in debug mode...
main_development.dart:1
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'C:\Users\my_project\build\windows\CMakeFiles\8d5ed7d16c2d77a07f2ed3d3c219134c\flutter_windows.dll.rule;C:\Users\my_project\build\windows\CMakeFiles\8126e6043f2fdff3a26fd3c5142bbc6d\flutter_assemble.rule' exited with code 1. [C:\Users\my_project\build\windows\flutter\flutter_assemble.vcxproj]
Exception: Build process failed.
Exited (sigterm)
```

Manually replacing the '\' and adding '/' at the end of each path fixed it:
```yaml
flutter:

  assets:
    - assets/audio/
    - assets/images/
    - assets/images/1_Interiors/
    - assets/images/1_Interiors/32x32/
    - assets/images/1_Interiors/32x32/Old_Stuff/
    - assets/images/1_Interiors/32x32/Room_Bulder_subfiles_32x32/
    - assets/images/1_Interiors/32x32/Theme_Sorter_32x32/
    - assets/images/1_Interiors/32x32/Theme_Sorter_Black_Shadow_32x32/
```
This is my flutter doctor:
```bash
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.19045.3324], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.19)
[√] Android Studio (version 2022.2)
[√] VS Code (version 1.81.1)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
```
